name: scotter_app_ui_kit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish black/Mulish-Light.ttf
          weight: 400
        - asset: assets/fonts/Mulish black/Mulish-Black.ttf
          weight: 700
        - asset: assets/fonts/Mulish black/Mulish-Bold.ttf
          weight: 900